[package]
name = "prollyglot-audio-pipewire"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
crossbeam-channel.workspace = true
prollyglot-core = { path = "../prollyglot-core" }

[target.'cfg(target_os = "linux")'.dependencies]
pipewire = { version = "0.10.1", features = ["v1_0_0"] }
prollyglot-audio-pipeline = { path = "../audio-pipeline" }
serde_json.workspace = true
sha2.workspace = true

[dev-dependencies]
serde_json.workspace = true
